# Default values for zulvit-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: kuplenik-ss
image:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  pullSecrets:
    - name: dockerhub-zulvit
